#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'taina puja'
        hostname: ubuntu-desktop
        username: taigot
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
        - name: firefox
        - name: gnome-3-38-2004
        - name: gtk-common-themes
        - name: snap-store
        - name: snapd-desktop-integration
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

